### ISSUE TITLE
ModuleNotFoundError: No module named 'marshmallow'

### ISSUE THREAD

**Issue by kingb** [jeff-vincent/flask-api#6]
I'm getting the following error when trying to run `main.py`

```i$ python main.py 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from create_post import CreatePost
  File "/home/king/proj/mentoring/flask-api/create_post.py", line 2, in <module>
    from models import Post
  File "/home/king/proj/mentoring/flask-api/models.py", line 2, in <module>
    from marshmallow import Schema, fields
ModuleNotFoundError: No module named 'marshmallow'
```
For this bug report, I'm purposefully leaving out the solution or additional information that might help you figure out the problem to let you recreate and debug it as a learning exercise. Do feel free to ask questions on this issue, and I'll make sure to respond.

**Comment by jeff-vincent** [comment]
I suspect that pipenv would prevent this. I've updated requirements.txt for now. Muchas gracias.
